Hw 2 count det
mat90x/made-cpp-2020-hw pull request #2
Opened 2020-09-29 20:04 UTC by mat90x

2020-10-01 13:05 UTC, xterrafunny requested changes

2020-10-01 13:05 UTC, xterrafunny commented on count_det/src/main.s
> +    mov r1, #1
Необходимо положить на стек значения регистров `r4-...`, значения которых изменяются во время работы функции, так как они могли хранить данные вне функции

2020-10-01 13:05 UTC, xterrafunny commented on count_det/src/main.s
> +
А здесь необходимо сделать `pop` со стека

2020-10-31 19:11 UTC, SweetWeakness commented
Нет ответа по PR. закрываю

2020-10-31 19:11 UTC, closed without merging